[tools]
go = "1.25.7"

[tasks.app]
description = "Install the Go application"
run = "rm -f $HOME/.local/bin/deck-game-installer && GOBIN=$HOME/.local/bin go install ./v2/cmd/deck-game-installer"

[tasks.servicemenu]
description = "Install the Dolphin service menu"
run = """
mkdir -p ~/.local/share/kio/servicemenus/
cp install-with-steam.desktop ~/.local/share/kio/servicemenus/
chmod +x ~/.local/share/kio/servicemenus/install-with-steam.desktop
"""

[tasks.install]
description = "Install the application and service menu"
depends = ["app", "servicemenu"]
